### ISSUE TITLE
Change RSN in plugin,

### ISSUE THREAD

**Issue by TanoakFe** [rhoiyds/osrs-streamers#15]
Hi can i please have my Rsn changed to names below, 
Tanoak
Tanoak alt
https://www.twitch.tv/tanoakfe

**Comment by WesleyM77** [comment]
Hey there, I just became a maintainer of this plugin. It looks like that link is broken now, I think I found your new twitch here: https://www.twitch.tv/tanoakosrs. If that's the case, I'll need to see a new clip confirming these accounts as I don't see any old streams/videos. Thanks!

**Comment by TanoakFe** [comment]
Hi, yes that is my new Twitch, thanks for replying,

Tanoak, Clip:
https://www.twitch.tv/tanoakosrs/clip/BlindingCrazyWheelDerp-_c9Q5xCO_AUXx9qb
Tanoak Hc, Clip:
https://clips.twitch.tv/InnocentDirtyNikudonAliens-LvSHW6PX4Ahs0kJL
Tanoak alt, Clip:
https://clips.twitch.tv/AmorphousGorgeousOkapiDBstyle-ruV2K30ta8JQ22nD
