### ISSUE TITLE
Wanting an account removed from a stream link

### ISSUE THREAD

**Issue by Pokelove666** [rhoiyds/osrs-streamers#16]
i changed my username on osrs but its showing someone else twitch channel on the OSRS Streamers plug in on runelite i would like the twitch link which is t.tv/un00000b be removed from my account  X M E because its incorrect i dont want it because its not mine thanks 

RSN USER: R 8 X

the link i want removed t.tv/un00000b

**Comment by WesleyM77** [comment]
Hey there, I just became a maintainer of this plugin. Just to confirm, you'd like "X M E" to be removed from your list, and add "R 8 X" added?

**Comment by Pokelove666** [comment]
hi how u doing no id like for u to remove anything associated with those username please the link t.ttv/un00000b i want it off from the names please thanks

**Comment by WesleyM77** [comment]
Sure thing! For verification purposes, can you make a quick video on your twitch stating that you'd like to be removed from the OSRS Streamers plugin? Link that here and make sure that it's available for non-subscribers and I can remove you from the plugin. Thanks!

**Comment by Pokelove666** [comment]
hello i cant make a vid cuse thats not my twitch channel the reason i needed it off was because the person that had that ttv plugin changed theyre name in game and i took the name so now it showed his link for twitch but this isnt my twitch account

**Comment by Pokelove666** [comment]
was it taken care of ?

**Comment by WesleyM77** [comment]
Yes, "X M E" is no longer linked to that streamer.
