### ISSUE TITLE
Twitch Name Change: Need Change on Plugin

### ISSUE THREAD

**Issue by slushiiiibtw** [rhoiyds/osrs-streamers#19]
Hello! I recently changed my name from Rs_Slushiiii to slushiiiibtw on Twitch. Can you please change it so that my RSN's: Slushiiii,  Prewerkout, Ratification, and Hcim To Zuk are no longer under twitch.tv/rs_slushiiii, but rather twitch.tv/slushiiiibtw? If you need any video proof it's on my channel. Thanks!

**Comment by WesleyM77** [comment]
Hey there, I just became a maintainer of this plugin. I'm going through the backlog of requests and should get yours processed today. I'll close this ticket when I've submitted to plugin-hub. Thanks for being so patient!
