### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by beckyosrs** [rhoiyds/osrs-streamers#20]
Hi there, I have tried multiple times to add myself to this and it doesn't ever update.

My twitch name is beckyosrs

Could you please assist me in getting myself added to the list, been streaming now since February 2021.

Thanks!

**Comment by WesleyM77** [comment]
Hey there, I just became a maintainer of this plugin. I'm going through the backlog of requests and should get yours processed today. I'll close this ticket when I've submitted to plugin-hub.

**Comment by beckyosrs** [comment]
Thank you! If you need any extra information or anything please don’t hesitate to ask. 

Discord is becky#7532 or you can message on Twitter beckyosrs or email here is fine :)

Thank you!
