### ISSUE TITLE
wont show my channel 

### ISSUE THREAD

**Issue by scoutllama** [rhoiyds/osrs-streamers#4]
hello lads my name and twitch is not being shown for other ppl with the plugin? my ign is Gucci x LV. and my twitch is https://www.twitch.tv/osrs_gucci_x_lv

**Comment by royporter7** [comment]
Hey! Thanks for letting me know. It looks like your account was added with the wrong capitilization the first time around. I'll fix that up in the next 24hrs or so.

**Comment by scoutllama** [comment]
Thank you so much for the Quick response  and its a really nice plugin! Nice job 😊

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

Fra: Roy Porter<mailto:notifications@github.com>
Sendt: 23. november 2020 02:09
Til: rhoiyds/osrs-streamers<mailto:osrs-streamers@noreply.github.com>
Cc: scoutllama<mailto:nymandprivat@outlook.dk>; Author<mailto:author@noreply.github.com>
Emne: Re: [rhoiyds/osrs-streamers] wont show my channel (#4)


Hey! Thanks for letting me know. It looks like your account was added with the wrong capitilization the first time around. I'll fix that up in the next 24hrs or so.

**Comment by scoutllama** [comment]
thanks for the quick response 👍

**Comment by royporter7** [comment]
Should all be fixed up now, mate. Thanks for logging the issue :) Let me know if there's any other problems or suggestions.
