### ISSUE TITLE
Add a link to the token creation page on the "invalid token" game message

### ISSUE THREAD

**Issue by ShaunDreclin** [rhoiyds/osrs-streamers#9]

**Comment by royporter7** [comment]
Great suggestion - it would certainly encourage more people to properly set up their token. 
Unfortunately Runelite devs aren't allowed to add links to the chatbox 
![Links not allowed](https://user-images.githubusercontent.com/6437024/104268019-49091a80-54d6-11eb-833e-9ee87b80693c.PNG)
However! The devs suggested I instead prompt people to type a chat command '::gettoken' which can automatically open a person to the token generation page. I think this is a great idea, and will go ahead with this. 
Let me know if you think it is the best solution :)

**Comment by ShaunDreclin** [comment]
That works! 😄

**Comment by royporter7** [comment]
Glad to hear! The feature is done, just waiting approval from the RuneLite devs and then the update will be live. 
If you ever have any further suggestions/bug reports, please don't hesitate in creating another post :D
